using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;


namespace DReportUtil.DBControl
{
    public class DBQry
    {
        public static string rpt1(string begin, string end)
        {
            string qry = string.Format(@"(SELECT DISTINCT(AA.TRANS_ID), AA.REVERSE_TRANS_ID AS ESREG_GUILGEE, HH.PRODUCT_NAME AS BAGTS, GG.CHANNEL_NAME AS SUWAG, AA.REGDATE AS SUNGASN_UDUR, AA.CARD_NUMBER AS CARD, BB.SUBSCRIBER_FNAME AS NER, DECODE(BB.SUBSCRIBER_STATUS, 0,'INACTIVE', 1,'ACTIVE', 'UNKNOWN') STATUS, SS.SUBTYPE_NAME AS TURUL, AA.STARTDATE AS EXLEX_XUGATSAA, AA.ENDDATE AS DUUSAX_XUGATSAA, AA.AMOUNT AS MUNGUN_DUN, DD.BRANCHNAME AS SALBAR, AA.USER_NAME AS SUNGALT_AJILTAN, AA.DESCR AS TAILBAR, BB.OPERATION_ID AS UUSGESEN_AJILTAN , AA.TOTAL_POINT AS UP_NEMEGDSEN, AA.SPEND_POINT AS UP_HASAGDSAN FROM (
        SELECT ORGACC.*,P.TOTAL_POINT,P.SPEND_POINT FROM (
        SELECT * FROM ACCOUNT_TRANSACTION WHERE REGDATE >= TO_DATE('{0}','YYYYMMDDHH24MISS') AND REGDATE <= TO_DATE('{1}','YYYYMMDDHH24MISS') AND PRODUCT_ID IN  (SELECT PRODUCT_ID FROM PRODUCT_CATALOG WHERE ISREPORT =1) AND AMOUNT !=0 AND CARD_NUMBER NOT IN ('8097603536532789', '2130152015', '2130139200') AND SUBSTR(CARD_NUMBER, 0,3) !='100' AND CALL_TYPE NOT IN (101,5,40)
        UNION ALL
        SELECT * FROM ACCOUNT_TRANSACTION WHERE REGDATE >= TO_DATE('{0}','YYYYMMDDHH24MISS') AND REGDATE <= TO_DATE('{1}','YYYYMMDDHH24MISS') AND PRODUCT_ID IS NULL  AND AMOUNT !=0 AND CARD_NUMBER NOT IN ('8097603536532789', '2130152015', '2130139200') AND SUBSTR(CARD_NUMBER, 0,3) !='100' AND CALL_TYPE=41
        UNION
        SELECT * FROM ACCOUNT_TRANSACTION WHERE REGDATE >= TO_DATE('{0}','YYYYMMDDHH24MISS') AND REGDATE <= TO_DATE('{1}','YYYYMMDDHH24MISS') AND DESCR LIKE '%FLASH%'
) ORGACC 
LEFT JOIN UPOINT_TRANSACTION P ON P.TRANS_ID = ORGACC.TRANS_ID
WHERE ORGACC.TRANS_ID NOT IN (SELECT TO_NUMBER(CDR_TRANS_ID) FROM D_ACCOUNT_CDR WHERE CDR_REGDATE >='{0}'  AND CDR_REGDATE <='{1}' AND CDR_TRANS_ID IS NOT NULL) AND RESULT = 0
) AA
LEFT JOIN T_DISH_CUSTOM BB ON AA.CARD_NUMBER = BB.CARD_NO
LEFT JOIN (SELECT AAA.BRANCHNAME, AAA.BRANCHID, BBB.USER_ID FROM RESELLER.T_Branch@unidishdb AAA, (SELECT * FROM RESELLER.Userinfo@unidishdb WHERE BRANCHID IS NOT NULL) BBB WHERE AAA.BRANCHID = BBB.BRANCHID) DD ON AA.USER_NAME = DD.USER_ID
LEFT JOIN TYPE_CHANNEL GG ON AA.CHANNEL_TYPE = GG.CHANNEL_ID
LEFT JOIN PRODUCT_CATALOG HH ON AA.PRODUCT_ID = HH.PRODUCT_ID
LEFT JOIN T_DISH_SUBSCRIBERTYPE SS ON BB.SUBSCRIBER_TYPE = SS.SUBTYPE_ID)

UNION ALL

(SELECT DISTINCT(AA.TRANS_ID), AA.REVERSE_TRANS_ID AS ESREG_GUILGEE, HH.PRODUCT_NAME AS BAGTS, GG.CHANNEL_NAME AS SUWAG, AA.REGDATE AS SUNGASN_UDUR, AA.CARD_NUMBER AS CARD, BB.SUBSCRIBER_FNAME AS NER, DECODE(BB.SUBSCRIBER_STATUS, 0,'INACTIVE', 1,'ACTIVE', 'UNKNOWN') STATUS, SS.SUBTYPE_NAME AS TURUL, AA.STARTDATE AS EXLEX_XUGATSAA, AA.ENDDATE AS DUUSAX_XUGATSAA, AA.AMOUNT AS MUNGUN_DUN, DD.BRANCHNAME AS SALBAR, AA.USER_NAME AS SUNGALT_AJILTAN, AA.DESCR AS TAILBAR, BB.OPERATION_ID AS UUSGESEN_AJILTAN , AA.TOTAL_POINT AS UP_NEMEGDSEN, AA.SPEND_POINT AS UP_HASAGDSAN FROM (
        SELECT ORGACC.*,P.TOTAL_POINT,P.SPEND_POINT FROM (
        SELECT * FROM ACCOUNT_TRANSACTION WHERE REGDATE >= TO_DATE('{0}','YYYYMMDDHH24MISS') AND REGDATE <= TO_DATE('{1}','YYYYMMDDHH24MISS') AND PRODUCT_ID IN  (SELECT PRODUCT_ID FROM PRODUCT_CATALOG WHERE ISREPORT =1) AND AMOUNT !=0 AND CARD_NUMBER NOT IN ('8097603536532789', '2130152015', '2130139200') AND SUBSTR(CARD_NUMBER, 0,3) !='100' AND CALL_TYPE NOT IN (101,5,40)
        UNION ALL
        SELECT * FROM ACCOUNT_TRANSACTION WHERE REGDATE >= TO_DATE('{0}','YYYYMMDDHH24MISS') AND REGDATE <= TO_DATE('{1}','YYYYMMDDHH24MISS') AND PRODUCT_ID IS NULL  AND AMOUNT !=0 AND CARD_NUMBER NOT IN ('8097603536532789', '2130152015', '2130139200') AND SUBSTR(CARD_NUMBER, 0,3) !='100' AND CALL_TYPE=41
        UNION
        SELECT * FROM ACCOUNT_TRANSACTION WHERE REGDATE >= TO_DATE('{0}','YYYYMMDDHH24MISS') AND REGDATE <= TO_DATE('{1}','YYYYMMDDHH24MISS') AND DESCR LIKE '%FLASH%'
) ORGACC 
LEFT JOIN UPOINT_TRANSACTION P ON P.TRANS_ID = ORGACC.TRANS_ID
WHERE ORGACC.TRANS_ID NOT IN (SELECT TO_NUMBER(CDR_TRANS_ID) FROM D_ACCOUNT_CDR WHERE CDR_REGDATE >='{0}'  AND CDR_REGDATE <='{1}' AND CDR_TRANS_ID IS NOT NULL) AND ORGACC.TRANS_ID NOT IN (SELECT TRANS_ID FROM UPOINT_TRANSACTION)
) AA
LEFT JOIN T_DISH_CUSTOM BB ON AA.CARD_NUMBER = BB.CARD_NO
LEFT JOIN (SELECT AAA.BRANCHNAME, AAA.BRANCHID, BBB.USER_ID FROM RESELLER.T_Branch@unidishdb AAA, (SELECT * FROM RESELLER.Userinfo@unidishdb WHERE BRANCHID IS NOT NULL) BBB WHERE AAA.BRANCHID = BBB.BRANCHID) DD ON AA.USER_NAME = DD.USER_ID
LEFT JOIN TYPE_CHANNEL GG ON AA.CHANNEL_TYPE = GG.CHANNEL_ID
LEFT JOIN PRODUCT_CATALOG HH ON AA.PRODUCT_ID = HH.PRODUCT_ID
LEFT JOIN T_DISH_SUBSCRIBERTYPE SS ON BB.SUBSCRIBER_TYPE = SS.SUBTYPE_ID)

UNION ALL

(SELECT DISTINCT(AA.TRANS_ID), AA.REVERSE_TRANS_ID AS ESREG_GUILGEE, HH.PRODUCT_NAME AS BAGTS, GG.CHANNEL_NAME AS SUWAG, AA.REGDATE AS SUNGASN_UDUR, AA.CARD_NUMBER AS CARD, BB.SUBSCRIBER_FNAME AS NER, DECODE(BB.SUBSCRIBER_STATUS, 0,'INACTIVE', 1,'ACTIVE', 'UNKNOWN') STATUS, SS.SUBTYPE_NAME AS TURUL, AA.STARTDATE AS EXLEX_XUGATSAA, AA.ENDDATE AS DUUSAX_XUGATSAA, AA.AMOUNT AS MUNGUN_DUN, DD.BRANCHNAME AS SALBAR, AA.USER_NAME AS SUNGALT_AJILTAN, AA.DESCR AS TAILBAR, BB.OPERATION_ID AS UUSGESEN_AJILTAN , AA.TOTAL_POINT AS UP_NEMEGDSEN, AA.SPEND_POINT AS UP_HASAGDSAN FROM (
        SELECT ORGACC.*,P.TOTAL_POINT,P.SPEND_POINT FROM (
        SELECT * FROM ACCOUNT_TRANSACTION WHERE REGDATE >= TO_DATE('{0}','YYYYMMDDHH24MISS') AND REGDATE <= TO_DATE('{1}','YYYYMMDDHH24MISS') AND PRODUCT_ID IN  (SELECT PRODUCT_ID FROM PRODUCT_CATALOG WHERE ISREPORT =1) AND AMOUNT !=0 AND CARD_NUMBER NOT IN ('8097603536532789', '2130152015', '2130139200') AND SUBSTR(CARD_NUMBER, 0,3) !='100' AND CALL_TYPE NOT IN (101,5,40)
        UNION ALL
        SELECT * FROM ACCOUNT_TRANSACTION WHERE REGDATE >= TO_DATE('{0}','YYYYMMDDHH24MISS') AND REGDATE <= TO_DATE('{1}','YYYYMMDDHH24MISS') AND PRODUCT_ID IS NULL  AND AMOUNT !=0 AND CARD_NUMBER NOT IN ('8097603536532789', '2130152015', '2130139200') AND SUBSTR(CARD_NUMBER, 0,3) !='100' AND CALL_TYPE=41
        UNION
        SELECT * FROM ACCOUNT_TRANSACTION WHERE REGDATE >= TO_DATE('{0}','YYYYMMDDHH24MISS') AND REGDATE <= TO_DATE('{1}','YYYYMMDDHH24MISS') AND DESCR LIKE '%FLASH%'
) ORGACC 
LEFT JOIN UPOINT_TRANSACTION P ON P.TRANS_ID = ORGACC.TRANS_ID
WHERE ORGACC.TRANS_ID NOT IN (SELECT TO_NUMBER(CDR_TRANS_ID) FROM D_ACCOUNT_CDR WHERE CDR_REGDATE >='{0}'  AND CDR_REGDATE <='{1}' AND CDR_TRANS_ID IS NOT NULL) AND ORGACC.TRANS_ID IN (SELECT DISTINCT(TRANS_ID) FROM UPOINT_TRANSACTION WHERE  RESULT != 0)
) AA
LEFT JOIN T_DISH_CUSTOM BB ON AA.CARD_NUMBER = BB.CARD_NO
LEFT JOIN (SELECT AAA.BRANCHNAME, AAA.BRANCHID, BBB.USER_ID FROM RESELLER.T_Branch@unidishdb AAA, (SELECT * FROM RESELLER.Userinfo@unidishdb WHERE BRANCHID IS NOT NULL) BBB WHERE AAA.BRANCHID = BBB.BRANCHID) DD ON AA.USER_NAME = DD.USER_ID
LEFT JOIN TYPE_CHANNEL GG ON AA.CHANNEL_TYPE = GG.CHANNEL_ID
LEFT JOIN PRODUCT_CATALOG HH ON AA.PRODUCT_ID = HH.PRODUCT_ID
LEFT JOIN T_DISH_SUBSCRIBERTYPE SS ON BB.SUBSCRIBER_TYPE = SS.SUBTYPE_ID)", begin, end);
            return qry;
        }
        public static string rpt2(string begin, string end)
        {
            string qry = string.Format(@"SELECT CC.REVERSE_TRANS_ID, GG.CHANNEL_NAME, AA.REGDATE, SUBSTR((AA.REGTIME+1000000),2,6) AS REGTIME, FF.NAME, AA.CARD_NO, BB.SUBSCRIBER_FNAME, 
DECODE(BB.SUBSCRIBER_STATUS, 0,'INACTIVE', 1,'ACTIVE', 'UNKNOWN') STATUS, AA.BEFORE_REMAINS, CC.AMOUNT, AA.AFTER_REMAINS, DD.BRANCHNAME, AA.USERNAME, CC.DESCR,TOTAL_POINT AS UP_NEMEGDSEN,SPEND_POINT AS UP_HASAGDSAN FROM 
(SELECT REGDATE, REGTIME, CARD_NO, BEFORE_REMAINS, AFTER_REMAINS, COUNTER_VALUE, USERNAME, TRANS_ID, BRANCH, CHANNEL_NAME, COUNTER_ID FROM D_ACCOUNT_RECHARGE 
WHERE COUNTER_ID = 1001 AND REGDATE >='{0}' AND REGDATE <='{1}' AND CARD_NO NOT IN ('8097603536532789', '2130152015') AND SUBSTR(CARD_NO, 0,3) !='100' ORDER BY SEQ_NO ASC ) AA 
LEFT JOIN T_DISH_CUSTOM BB ON AA.CARD_NO = BB.CARD_NO LEFT JOIN ACCOUNT_TRANSACTION CC ON AA.TRANS_ID = CC.TRANS_ID 
LEFT JOIN (SELECT AAA.BRANCHNAME, AAA.BRANCHID, BBB.USER_ID FROM RESELLER.T_Branch@unidishdb AAA, (SELECT * FROM RESELLER.Userinfo@unidishdb WHERE BRANCHID IS NOT NULL) BBB 
WHERE AAA.BRANCHID = BBB.BRANCHID) DD ON AA.USERNAME = DD.USER_ID 
LEFT JOIN D_COUNTERS FF ON AA.COUNTER_ID = FF.COUNTER_ID 
LEFT JOIN TYPE_CHANNEL GG ON AA.CHANNEL_NAME = GG.CHANNEL_ID
LEFT JOIN (SELECT * FROM UPOINT_TRANSACTION WHERE LENGTH(BILL_NUMBER)='24') UU ON UU.TRANS_ID = AA.TRANS_ID", begin, end);
            return qry;
        }
        public static string rpt6(string begin, string end)
        {
            string qry = string.Format(@"SELECT AA.REVERSE_TRANS_ID, HH.PRODUCT_NAME, GG.CHANNEL_NAME, AA.REGDATE, AA.CARD_NUMBER, BB.SUBSCRIBER_FNAME, DECODE(BB.SUBSCRIBER_STATUS, 0,'INACTIVE', 1,'ACTIVE', 'UNKNOWN') STATUS, SS.SUBTYPE_NAME, AA.STARTDATE, AA.ENDDATE, AA.AMOUNT, DD.BRANCHNAME, AA.USER_NAME, AA.DESCR, BB.OPERATION_ID FROM (SELECT * FROM ACCOUNT_TRANSACTION WHERE REGDATE >= TO_DATE('{0}','YYYYMMDDHH24MISS') AND REGDATE <= TO_DATE('{1}','YYYYMMDDHH24MISS') AND CALL_TYPE =9 AND CHANNEL_TYPE=9 AND AMOUNT=0 AND CARD_NUMBER NOT IN ('8097603536532789') AND DESCR LIKE 'Үнэгүй%' ORDER BY TRANS_ID ASC) AA
LEFT JOIN T_DISH_CUSTOM BB ON AA.CARD_NUMBER = BB.CARD_NO
LEFT JOIN (SELECT AAA.BRANCHNAME, AAA.BRANCHID, BBB.USER_ID FROM RESELLER.T_Branch@unidishdb AAA, (SELECT * FROM RESELLER.Userinfo@unidishdb WHERE BRANCHID IS NOT NULL) BBB WHERE AAA.BRANCHID = BBB.BRANCHID) DD ON AA.USER_NAME = DD.USER_ID
LEFT JOIN TYPE_CHANNEL GG ON AA.CHANNEL_TYPE = GG.CHANNEL_ID
LEFT JOIN PRODUCT_CATALOG HH ON AA.PRODUCT_ID = HH.PRODUCT_ID
LEFT JOIN T_DISH_SUBSCRIBERTYPE SS ON BB.SUBSCRIBER_TYPE = SS.SUBTYPE_ID", begin, end);
            return qry;
        }
        public static string rpt3(string begin, string end)
        {
            string qry = string.Format(@"SELECT CC.REVERSE_TRANS_ID, NN.PRODUCT_NAME, FF.CHANNEL_NAME, AA.CDR_REGDATE, VV.NAME, AA.CARD_NO, BB.SUBSCRIBER_FNAME, DECODE(BB.SUBSCRIBER_STATUS, 0,'INACTIVE', 1,'ACTIVE', 'UNKNOWN') STATUS, CC.STARTDATE, CC.ENDDATE, AA.CDR_BEFORE_BALANCE, AA.CDR_USED_AMOUNT, AA.CDR_AFTER_BALANCE, CT.CALL_TYPE_NAME, DD.BRANCHNAME, CC.USER_NAME, CC.DESCR, BB.OPERATION_ID FROM (SELECT * FROM D_ACCOUNT_CDR WHERE CDR_REGDATE >= {0} AND CDR_REGDATE <= {1} AND CDR_USED_COUNTERS=1001 AND SUBSTR(CARD_NO, 0,3) !='100' AND CARD_NO NOT IN ('8097603536532789', '2130152015', '2130123096') ORDER BY CDR_SEQ ASC ) AA
LEFT JOIN T_DISH_CUSTOM BB ON AA.CARD_NO = BB.CARD_NO
LEFT JOIN ACCOUNT_TRANSACTION CC ON AA.CDR_TRANS_ID = CC.TRANS_ID
LEFT JOIN (SELECT AAA.BRANCHNAME, AAA.BRANCHID, BBB.USER_ID FROM RESELLER.T_Branch@unidishdb AAA, (SELECT * FROM RESELLER.Userinfo@unidishdb WHERE BRANCHID IS NOT NULL) BBB WHERE AAA.BRANCHID = BBB.BRANCHID) DD ON AA.CDR_REG_USER = DD.USER_ID
LEFT JOIN TYPE_CHANNEL FF ON AA.CDR_CHANNEL_TYPE = FF.CHANNEL_ID
LEFT JOIN TYPE_CALL_TYPE CT ON CC.CALL_TYPE = CT.CALL_TYPE_ID
LEFT JOIN D_COUNTERS VV ON AA.CDR_USED_COUNTERS = VV.COUNTER_ID
LEFT JOIN PRODUCT_CATALOG NN ON CC.PRODUCT_ID = NN.PRODUCT_ID WHERE CC.CALL_TYPE !=10", begin, end);
            return qry;
        }

        public static string rpt5(string begin, string end)
        {
            string qry = string.Format(@"select installer, a.CARD_NO, amount, DECODE(a.amount, 500,'Илүү багц', 1000,'Үлэмж багц') Bagtsiin_ner, c.name, a.INSERT_DATE, b.CREATE_DATE from installer_promotion_tbl_new a
left join t_dish_custom b on a.CARD_NO = b.CARD_NO
left join w_item_bundle c on b.bundle_id = c.id
where a.INSERT_DATE>=to_date('{0}','yyyymmddhh24miss')
and a.INSERT_DATE<=to_date('{1}','yyyymmddhh24miss') and
b.CREATE_DATE>=to_date('20191130000000','yyyymmddhh24miss')
and b.CREATE_DATE<=to_date('20191231235959','yyyymmddhh24miss')
and a.type=1 and a.INSTALLER in ('installer_munkhtur','installer_baterdene_n','installer_sergei')", begin, end);
            return qry;
        }

        public static string rpt4(string begin, string end)
        {
            string qry = string.Format(@"SELECT CC.REVERSE_TRANS_ID, CC.TRANS_ID, NN.PRODUCT_NAME, FF.CHANNEL_NAME, AA.CDR_REGDATE, VV.NAME, AA.CARD_NO, BB.SUBSCRIBER_FNAME, DECODE(BB.SUBSCRIBER_STATUS, 0,'INACTIVE', 1,'ACTIVE', 'UNKNOWN') STATUS, CC.STARTDATE, CC.ENDDATE, AA.CDR_BEFORE_BALANCE, AA.CDR_USED_AMOUNT, AA.CDR_AFTER_BALANCE, CT.CALL_TYPE_NAME, DD.BRANCHNAME, CC.USER_NAME, CC.DESCR, OO.NAME_ENG, OO.NAME_MON FROM (SELECT * FROM D_ACCOUNT_CDR WHERE CDR_REGDATE >= {0} AND CDR_REGDATE <= {1} AND CDR_USED_COUNTERS IS NOT NULL AND SUBSTR(CARD_NO, 0,3) !='100' AND CARD_NO NOT IN ('8097603536532789', '2130152015', '2130123096') ORDER BY CDR_SEQ ASC ) AA
LEFT JOIN T_DISH_CUSTOM BB ON AA.CARD_NO = BB.CARD_NO
LEFT JOIN ACCOUNT_TRANSACTION CC ON AA.CDR_TRANS_ID = CC.TRANS_ID
LEFT JOIN (SELECT AAA.BRANCHNAME, AAA.BRANCHID, BBB.USER_ID FROM RESELLER.T_Branch@unidishdb AAA, (SELECT * FROM RESELLER.Userinfo@unidishdb WHERE BRANCHID IS NOT NULL) BBB WHERE AAA.BRANCHID = BBB.BRANCHID) DD ON AA.CDR_REG_USER = DD.USER_ID
LEFT JOIN TYPE_CHANNEL FF ON CC.CHANNEL_TYPE = FF.CHANNEL_ID
LEFT JOIN TYPE_CALL_TYPE CT ON CC.CALL_TYPE = CT.CALL_TYPE_ID
LEFT JOIN D_COUNTERS VV ON AA.CDR_USED_COUNTERS = VV.COUNTER_ID
LEFT JOIN PRODUCT_CATALOG NN ON CC.PRODUCT_ID = NN.PRODUCT_ID 
LEFT JOIN TV_CONTENT OO ON CC.CONTENT_ID = OO.ID WHERE CC.CALL_TYPE =10", begin,end);
            return qry;
        }

        public static string rpt7(string begin, string end)
        {
            string qry = string.Format(@" SELECT CARD_NO, SUBSCRIBER_FNAME, SUBSCRIBER_LNAME, CERTIFICATE_NO, C.BRANCH_NAME, B.USER_NAME, D.NAME, TO_CHAR(CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS CREATE_DATE, '180000' AS LIZING_AMOUNT, '60000' AS DISCOUNT, PRICE  FROM T_DISH_CUSTOM A
LEFT JOIN SYSTEM_YES_USER_TBL B ON B.USER_NAME = A. OPERATION_ID
LEFT JOIN SYSTEM_BRANCH_LOCATION C ON C.BRANCH_ID = B.BRANCH_ID
LEFT JOIN W_ITEM_BUNDLE D ON D.ID = A.BUNDLE_ID
WHERE BUNDLE_ID IN (SELECT ID FROM W_ITEM_BUNDLE WHERE ID IN (3156, 3154, 3153, 3151, 3150, 3157, 3141, 3142, 3144, 3145, 3147, 3148, 3136, 3135, 3133, 3132, 3130, 3129) AND TYPE = 16) AND CREATE_DATE >= TO_DATE('{0}', 'YYYYMMDDHH24MISS') AND CREATE_DATE <= TO_DATE('{1}', 'YYYYMMDDHH24MISS')
UNION ALL (
SELECT CARD_NO, SUBSCRIBER_FNAME, SUBSCRIBER_LNAME, CERTIFICATE_NO, C.BRANCH_NAME, B.USER_NAME, D.NAME, TO_CHAR(CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS CREATE_DATE, '180000' AS LIZING_AMOUNT, '10000' AS DISCOUNT, PRICE   FROM T_DISH_CUSTOM A
LEFT JOIN SYSTEM_YES_USER_TBL B ON B.USER_NAME = A. OPERATION_ID
LEFT JOIN SYSTEM_BRANCH_LOCATION C ON C.BRANCH_ID = B.BRANCH_ID
LEFT JOIN W_ITEM_BUNDLE D ON D.ID = A.BUNDLE_ID
WHERE BUNDLE_ID IN (SELECT ID FROM W_ITEM_BUNDLE WHERE ID IN (3149, 3155, 3131, 3152, 3146, 3134, 3143, 3128, 3140) AND TYPE = 16) AND CREATE_DATE >= TO_DATE('{0}', 'YYYYMMDDHH24MISS') AND CREATE_DATE <= TO_DATE('{1}', 'YYYYMMDDHH24MISS')
)
UNION ALL (
SELECT CARD_NO, SUBSCRIBER_FNAME, SUBSCRIBER_LNAME, CERTIFICATE_NO, C.BRANCH_NAME, B.USER_NAME, D.NAME, TO_CHAR(CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS CREATE_DATE, '120000' AS LIZING_AMOUNT, '50000' AS DISCOUNT, PRICE   FROM T_DISH_CUSTOM A
LEFT JOIN SYSTEM_YES_USER_TBL B ON B.USER_NAME = A. OPERATION_ID
LEFT JOIN SYSTEM_BRANCH_LOCATION C ON C.BRANCH_ID = B.BRANCH_ID
LEFT JOIN W_ITEM_BUNDLE D ON D.ID = A.BUNDLE_ID
WHERE BUNDLE_ID IN (SELECT ID FROM W_ITEM_BUNDLE WHERE ID IN (3137) AND TYPE = 16) AND CREATE_DATE >= TO_DATE('{0}', 'YYYYMMDDHH24MISS') AND CREATE_DATE <= TO_DATE('{1}', 'YYYYMMDDHH24MISS')
)
UNION ALL (
SELECT CARD_NO, SUBSCRIBER_FNAME, SUBSCRIBER_LNAME, CERTIFICATE_NO, C.BRANCH_NAME, B.USER_NAME, D.NAME, TO_CHAR(CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS CREATE_DATE, '120000' AS LIZING_AMOUNT, '85000' AS DISCOUNT, PRICE   FROM T_DISH_CUSTOM A
LEFT JOIN SYSTEM_YES_USER_TBL B ON B.USER_NAME = A. OPERATION_ID
LEFT JOIN SYSTEM_BRANCH_LOCATION C ON C.BRANCH_ID = B.BRANCH_ID
LEFT JOIN W_ITEM_BUNDLE D ON D.ID = A.BUNDLE_ID
WHERE BUNDLE_ID IN (SELECT ID FROM W_ITEM_BUNDLE WHERE ID IN (3138, 3139) AND TYPE = 16) AND CREATE_DATE >= TO_DATE('{0}', 'YYYYMMDDHH24MISS') AND CREATE_DATE <= TO_DATE('{1}', 'YYYYMMDDHH24MISS')
)
UNION ALL (
SELECT CARD_NO, SUBSCRIBER_FNAME, SUBSCRIBER_LNAME, CERTIFICATE_NO, C.BRANCH_NAME, B.USER_NAME, D.NAME, TO_CHAR(CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS CREATE_DATE, '180000' AS LIZING_AMOUNT, '50000' AS DISCOUNT, PRICE   FROM T_DISH_CUSTOM A
LEFT JOIN SYSTEM_YES_USER_TBL B ON B.USER_NAME = A. OPERATION_ID
LEFT JOIN SYSTEM_BRANCH_LOCATION C ON C.BRANCH_ID = B.BRANCH_ID
LEFT JOIN W_ITEM_BUNDLE D ON D.ID = A.BUNDLE_ID
WHERE BUNDLE_ID IN (SELECT ID FROM W_ITEM_BUNDLE WHERE ID IN (3171, 3175, 3179) AND TYPE = 16) AND CREATE_DATE >= TO_DATE('{0}', 'YYYYMMDDHH24MISS') AND CREATE_DATE <= TO_DATE('{1}', 'YYYYMMDDHH24MISS')
)
UNION ALL (
SELECT CARD_NO, SUBSCRIBER_FNAME, SUBSCRIBER_LNAME, CERTIFICATE_NO, C.BRANCH_NAME, B.USER_NAME, D.NAME, TO_CHAR(CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS CREATE_DATE, '240000' AS LIZING_AMOUNT, '60000' AS DISCOUNT, PRICE   FROM T_DISH_CUSTOM A
LEFT JOIN SYSTEM_YES_USER_TBL B ON B.USER_NAME = A. OPERATION_ID
LEFT JOIN SYSTEM_BRANCH_LOCATION C ON C.BRANCH_ID = B.BRANCH_ID
LEFT JOIN W_ITEM_BUNDLE D ON D.ID = A.BUNDLE_ID
WHERE BUNDLE_ID IN (SELECT ID FROM W_ITEM_BUNDLE WHERE ID IN (3172, 3173, 3176, 3177, 3180, 3181 ) AND TYPE = 16) AND CREATE_DATE >= TO_DATE('{0}', 'YYYYMMDDHH24MISS') AND CREATE_DATE <= TO_DATE('{1}', 'YYYYMMDDHH24MISS')
)
UNION ALL (
SELECT CARD_NO, SUBSCRIBER_FNAME, SUBSCRIBER_LNAME, CERTIFICATE_NO, C.BRANCH_NAME, B.USER_NAME, D.NAME, TO_CHAR(CREATE_DATE, 'YYYY-MM-DD HH24:MI:SS') AS CREATE_DATE, '180000' AS LIZING_AMOUNT, '50000' AS DISCOUNT, PRICE   FROM T_DISH_CUSTOM A
LEFT JOIN SYSTEM_YES_USER_TBL B ON B.USER_NAME = A. OPERATION_ID
LEFT JOIN SYSTEM_BRANCH_LOCATION C ON C.BRANCH_ID = B.BRANCH_ID
LEFT JOIN W_ITEM_BUNDLE D ON D.ID = A.BUNDLE_ID
WHERE BUNDLE_ID IN (SELECT ID FROM W_ITEM_BUNDLE WHERE ID IN (3174, 3178, 3182 ) AND TYPE = 16) AND CREATE_DATE >= TO_DATE('{0}', 'YYYYMMDDHH24MISS') AND CREATE_DATE <= TO_DATE('{1}', 'YYYYMMDDHH24MISS')
)", begin, end);
            return qry;
        }

        public static string rpt8(string begin, string end)
        {
            string qry = string.Format(@"select  CARD_NUMBER, AMOUNT, b.PRODUCT_NAME, a.STARTDATE, enddate, REGDATE,  USER_NAME, DESCR from uni_dish.account_transaction a
left join PRODUCT_CATALOG b on a.PRODUCT_ID = b.PRODUCT_ID
where REGDATE >= TO_DATE('{0}','yyyymmddhh24miss') and REGDATE <= TO_DATE('{1}','yyyymmddhh24miss') and amount = 0 and DESCR like 'нээлтийн%' and a.CARD_NUMBER not like '100%'" , begin , end);
            return qry;
        }

        public static string rpt9(string begin, string end)
        {
            string qry = string.Format(@"SELECT Y.REVERSE_TRANS_ID,X.TRANS_ID,X.CARD_NO,X.BILL_NUMBER,D.PRODUCT_NAME,E.CHANNEL_NAME,P.BRANCHNAME,Y.USER_NAME,F.CALL_TYPE_NAME,Y.REGDATE,X.BONUS_AMOUNT,X.TOTAL_POINT AS NEMEGDSEN_UPOINT,X.SPEND_POINT AS ZARTSUULSAN_UPOINT 
FROM UNI_DISH.UPOINT_TRANSACTION X
LEFT JOIN UNI_DISH.ACCOUNT_TRANSACTION Y ON Y.TRANS_ID=X.TRANS_ID
LEFT JOIN UNI_DISH.PRODUCT_CATALOG D ON D.PRODUCT_ID = Y.PRODUCT_ID
LEFT JOIN UNI_DISH.TYPE_CHANNEL E ON E.CHANNEL_ID=Y.CHANNEL_TYPE
LEFT JOIN UNI_DISH.TYPE_CALL_TYPE F ON F.CALL_TYPE_ID=Y.CALL_TYPE
LEFT JOIN RESELLER.T_BRANCH@unidishdb P ON P.BRANCHID=Y.BRANCH
WHERE INSERTDATE>=TO_DATE('{0}','YYYYMMDDHH24MISS') AND INSERTDATE<=TO_DATE('{1}','YYYYMMDDHH24MISS') AND MESSAGE='АМЖИЛТТАЙ' AND SUBSTR(CARD_NO,1,1)!=1 AND 
CARD_NO NOT IN ('8097603536532789','2130152015')", begin ,end);
                return qry;
        }

        public static string rpt10(string begin, string end)
        {
            string qry = string.Format(@"SELECT A.CARD_NO, SUBSCRIBER_FNAME, SUBSCRIBER_LNAME, CERTIFICATE_NO, BRANCH_NAME, CREATE_USER, LEASING_NAME, A.CREATE_DATE, LEASING_BALANCE FROM (
SELECT CARD_NO, LEASING_NAME, LEASING_BALANCE, CREATE_USER, CREATE_DATE FROM (
SELECT CARD_NO, PROMOTION_NAME AS LEASING_NAME, CREATE_USER, CREATE_DATE, LEASING_BALANCE FROM (
SELECT CARD_NO, PROMOTION_ID, CREATE_USER, CREATE_DATE, SUM(LEASING_BALANCE) AS LEASING_BALANCE FROM (
SELECT CARD_NO, PROMOTION_ID, CREATE_USER, CREATE_DATE, LEASING_BALANCE FROM ( 
SELECT CARD_NO, PROMOTION_ID, CREATE_USER, CREATE_DATE, SUM(DEVICE_PRICE) AS LEASING_BALANCE FROM (
SELECT CARD_NO, PROMOTION_ID, CREATE_USER, TO_CHAR(CREATE_DATE, 'YYYY/MM/DD') AS CREATE_DATE, DEVICE_PRICE FROM D_PRODUCT_PLAN 
where updated_date > TO_DATE('20170101000000', 'YYYYMMDDHH24MISS') ) GROUP BY CARD_NO, PROMOTION_ID, CREATE_USER, CREATE_DATE
) UNION ALL (
SELECT CARD_NO, PROMOTION_ID, CREATE_USER, CREATE_DATE, SUM(DEVICE_PRICE) AS LEASING_BALANCE FROM (
SELECT CARD_NO, PROMOTION_ID, CREATE_USER, TO_CHAR(CREATE_DATE, 'YYYY/MM/DD') AS CREATE_DATE, DEVICE_PRICE FROM D_PRODUCT_PLAN 
where TRANSID IS NULL ) GROUP BY CARD_NO, PROMOTION_ID, CREATE_USER, CREATE_DATE
) UNION ALL (
SELECT CARD_NO, PROMOTION_ID, CREATE_USER, CREATE_DATE, SUM(DEVICE_PRICE) AS LEASING_BALANCE FROM (
SELECT CARD_NO, PROMOTION_ID, CREATE_USER, TO_CHAR(CREATE_DATE, 'YYYY/MM/DD') AS CREATE_DATE, DEVICE_PRICE FROM D_PRODUCT_PLAN 
where TRANSID IS NOT NULL AND UPDATED_DATE IS NULL ) GROUP BY CARD_NO, PROMOTION_ID, CREATE_USER, CREATE_DATE
) ) GROUP BY CARD_NO, PROMOTION_ID, CREATE_USER, CREATE_DATE ) A LEFT JOIN D_PROMOTION_ID B ON A.PROMOTION_ID = B.ID
) UNION ALL (
SELECT A.CARD_NO, 'FLASH_LEASING' AS LEASING_NAME, LEASING_BALANCE, CREATED_USER AS CREATE_USER, TO_CHAR(CREATE_DATE, 'YYYY/MM/DD') AS CREATE_DATE FROM (
SELECT CARD_NO, SUM(LIMIT) AS LEASING_BALANCE FROM (
SELECT CARD_NO, LIMIT FROM (
SELECT CARD_NO, SUM(AMOUNT) AS LIMIT FROM FLASH_LEASING_CDR WHERE CARD_NO IN ( SELECT CARD_NO FROM FLASH_LEASING WHERE CREATE_DATE <= TO_DATE('{1}', 'YYYYMMDDHH24MISS') )
AND CREATE_DATE > TO_DATE('{0}', 'YYYYMMDDHH24MISS') GROUP BY CARD_NO
) UNION ALL (
SELECT CARD_NO, LIMIT FROM FLASH_LEASING WHERE CREATE_DATE <= TO_DATE('{1}', 'YYYYMMDDHH24MISS') AND CREATE_DATE >= TO_DATE('{0}', 'YYYYMMDDHH24MISS')
) ) GROUP BY CARD_NO
) A LEFT JOIN FLASH_LEASING B ON A.CARD_NO = B.CARD_NO
) ) A 
LEFT JOIN T_DISH_CUSTOM B ON A.CARD_NO = B.CARD_NO
LEFT JOIN SYSTEM_YES_USER_TBL C ON A.CREATE_USER = C.USER_NAME
LEFT JOIN SYSTEM_BRANCH_LOCATION D ON C.BRANCH_ID = D.BRANCH_ID", begin, end);
            return qry;
        }
        public static string rpt11(string begin, string end)
        {
            string qry = string.Format(@"select installer, a.CARD_NO, a.amount, DECODE(a.amount, 500,'Илүү багц', 1000,'Үлэмж багц') amount, c.name, a.INSERT_DATE, b.CREATE_DATE from installer_promotion_tbl_new a
left join t_dish_custom b on a.CARD_NO = b.CARD_NO
left join w_item_bundle c on b.bundle_id = c.id
where a.INSERT_DATE>=to_date('{0}','yyyymmddhh24miss')
and a.INSERT_DATE<=to_date('{1}','yyyymmddhh24miss') and
b.CREATE_DATE>=to_date('20191216000000','yyyymmddhh24miss')
and b.CREATE_DATE<=to_date('20191231235959','yyyymmddhh24miss')
and a.type = 1 and a.INSTALLER = 'dd_darkhan_1' ", begin, end);
            return qry;
        }

        public static string rpt12(string begin, string end)
        {
            string qry = string.Format(@"select installer, a.CARD_NO, a.amount, DECODE(a.amount, 500,'Илүү багц', 1000,'Үлэмж багц') Bagtsiin_ner, c.name, a.INSERT_DATE, b.CREATE_DATE from installer_promotion_tbl_new a
left join t_dish_custom b on a.CARD_NO = b.CARD_NO
left join w_item_bundle c on b.bundle_id = c.id
where a.INSERT_DATE>=to_date('{0}','yyyymmddhh24miss')
and a.INSERT_DATE<=to_date('{1}','yyyymmddhh24miss') and
b.CREATE_DATE>=to_date('20191216000000','yyyymmddhh24miss')
and b.CREATE_DATE<=to_date('20191231235959','yyyymmddhh24miss')
and a.type = 1 and a.INSTALLER = 'dd_darkhan_1'", begin, end);
            return qry;
        }

        public static string rpt13(string begin, string end)
        {
            string qry = string.Format(@"select a.trans_id, card_number, c.PRODUCT_NAME, d.name_eng AS CONTENT_NAME, b.STARTDATE, b.ENDDATE, b.DESCR, vcontent, unitel, ddish, unitel_amount, ddish_amount, regdate  from UNINEGJ_REPORT a
left join ACCOUNT_TRANSACTION b on b.TRANS_ID  = a.TRANS_ID
left join product_catalog c on c.product_id = B.product_id
left join TV_CONTENT d on d.id = b.CONTENT_ID
where  b.REGDATE >= to_date('{0}','yyyymmddhh24miss') and b.REGDATE <= to_date('{1}','yyyymmddhh24miss')
and b.CARD_NUMBER != '8097603536532789' and b.CARD_NUMBER not like '100%' AND B.PRODUCT_ID != 45
UNION ALL
select a.trans_id, card_number, c.PRODUCT_NAME, d.CONTENT_NAME AS CONTENT_NAME, b.STARTDATE, b.ENDDATE, b.DESCR, vcontent, unitel, ddish, unitel_amount, ddish_amount, regdate  from UNINEGJ_REPORT a
left join ACCOUNT_TRANSACTION b on b.TRANS_ID  = a.TRANS_ID
left join product_catalog c on c.product_id = B.product_id
left join D_PPV_EVENT_ID_NAME d on d.id = b.CONTENT_ID
where  b.REGDATE >= to_date('{0}','yyyymmddhh24miss') and b.REGDATE <= to_date('{1}','yyyymmddhh24miss')
and b.CARD_NUMBER != '8097603536532789' and b.CARD_NUMBER not like '100%' AND B.PRODUCT_ID = 45", begin ,end);
            return qry;
        }
        public static string rpt14(string begin, string end)
        {
            string qry = string.Format(@"select q.REVERSE_TRANS_ID, l.PRODUCT_NAME, ch.CHANNEL_NAME, substr(r.CDR_REGDATE, 0, 8) as REGDATE, substr(r.CDR_REGDATE, 9, 14) as REGTIME, c.NAME as VirtualAccount,
r.CARD_NO, t.SUBSCRIBER_FNAME, q.STARTDATE, q.ENDDATE, r.CDR_BEFORE_BALANCE, r.CDR_USED_AMOUNT as AMOUNT, r.CDR_AFTER_BALANCE, ct.CALL_TYPE_NAME, B.Branchname, q.USER_NAME,  
q.DESCR from uni_dish.D_ACCOUNT_CDR r 
left join uni_dish.T_DISH_CUSTOM t on t.CARD_NO = R.CARD_NO 
left join uni_dish.ACCOUNT_TRANSACTION q on q.TRANS_ID = r.CDR_TRANS_ID 
left join RESELLER.Userinfo@unidishdb u on q.USER_NAME = U.User_Id 
left join RESELLER.T_Branch@unidishdb b on U.Branchid = B.Branchid 
left join uni_dish.Type_Channel ch on q.Channel_Type = Ch.Channel_Id 
left join uni_dish.TYPE_CALL_TYPE ct on q.Call_Type = ct.call_type_id 
left join uni_dish.D_COUNTERS c on c.COUNTER_ID = R.CDR_USED_COUNTERS 
left join uni_dish.PRODUCT_CATALOG l on l.PRODUCT_ID = q.PRODUCT_ID
where  substr(r.CDR_REGDATE, 0, 8) >= '{0}' and substr(r.CDR_REGDATE, 0, 8) <= '{1}' and t.SUBSCRIBER_STATUS = '1' and r.CDR_USED_COUNTERS! = '1001' AND r.CARD_NO not in ('8097603536532789', '2130152015') AND r.CARD_NO not like '100%'", begin ,end);
            return qry;
        }
        public static string rpt15(string begin, string end)
        {
            string qry = string.Format(@"select * from (
select installer, a.CARD_NO, amount, INSERT_DATE, b.CREATE_DATE from uni_dish.installer_promotion_tbl_new a
left join uni_dish.t_dish_custom b on a.CARD_NO = b.CARD_NO
where INSERT_DATE>=to_date('{0}','yyyymmddhh24miss')
and INSERT_DATE<=to_date('{1}','yyyymmddhh24miss') and type=1
 ) sub1 order by 4 asc", begin, end);
            return qry;
        }

        public static string rpt16(string begin, string end)
        {
            string qry = string.Format(@"SELECT CONTRACT_ID, GER_NUMBER, CARD_NUMBER, PHONE_NO ADMIN_NUMBER, SUBSCRIBER_LNAME||' '||SUBSCRIBER_FNAME OVOG_NER, PRODUCT_NAME AS SERVICE_TYPE, SUBSCRIBER_TYPE, BRANCH_NAME AS USER_BRANCH_NAME, OPERATION_ID ACTIVE_USER, TO_CHAR(CREATE_DATE, 'YYYY/MM/DD') ACTIVE_TIME, CONNECT_TIME, SALE_TYPE, BASIC_AMOUNT, DISCOUNT, SALE_AMOUNT, DOWN_PAYMENT, LEASE_PERIOD, LEASE_FEE, LEASE_AMOUNT, TOTAL_AMOUNT, POLICY_NAME, IS_COMPLETE FROM (
SELECT CARD_NUMBER, PRODUCT_ID, POLICY_ID, POLICY_NAME, GER_NUMBER, CONTRACT_ID, CONNECT_TIME, BASIC_AMOUNT, DISCOUNT, SALE_AMOUNT, DOWN_PAYMENT, LEASE_PERIOD, LEASE_FEE, LEASE_AMOUNT, TOTAL_AMOUNT, SALE_TYPE, IS_COMPLETE FROM (
SELECT A.CARD_NO CARD_NUMBER, PRODUCT_ID, BUNDLE_ID AS POLICY_ID, BUNDLE_NAME POLICY_NAME, GER_NUMBER, CONTRACT_ID, CONNECTED_DATE CONNECT_TIME, BASIC_AMOUNT, DISCOUNT, SALE_AMOUNT, DOWN_PAYMENT, LEASE_PERIOD, LEASE_FEE, LEASE_AMOUNT, TOTAL_AMOUNT, SALE_TYPE, IS_COMPLETE FROM (
SELECT CARD_NO, STB_NO, BUNDLE_ID, BUNDLE_NAME, BASIC_AMOUNT, DISCOUNT, SALE_AMOUNT, DOWN_PAYMENT, LEASE_PERIOD, LEASE_FEE, LEASE_AMOUNT, TOTAL_AMOUNT, SALE_TYPE, IS_COMPLETE FROM (
SELECT CARD_NO, STB_NO, BUNDLE_ID, BUNDLE_NAME, PRICE BASIC_AMOUNT, 0 DISCOUNT, PRICE SALE_AMOUNT, 0 DOWN_PAYMENT, 0 LEASE_PERIOD, 0 LEASE_FEE, 0 LEASE_AMOUNT, PRICE TOTAL_AMOUNT, DECODE(SERVICE_TYPE, 1, 'CASH') AS SALE_TYPE, IS_COMPLETE FROM (
SELECT CARD_NO, STB_NO, BUNDLE_ID, BUNDLE_NAME, PRICE, DEPOSIT_PERCENT, DEPOSIT_PRICE, SERVICE_TYPE, IS_COMPLETE FROM T_DISH_CUSTOM_BRIEF A LEFT JOIN W_BUNDLE B ON A.BUNDLE_ID = B.ID WHERE A.IS_PREPAID = 2 AND CARD_NO NOT LIKE '100%'
) WHERE SERVICE_TYPE = 1
) UNION ALL (
SELECT CARD_NO, STB_NO, A.BUNDLE_ID, BUNDLE_NAME, BASIC_AMOUNT, DISCOUNT, ( BASIC_AMOUNT - DOWN_PAYMENT ) SALE_AMOUNT, DOWN_PAYMENT, PROMOTION_DURATION AS LEASE_PERIOD, ( DOWN_PAYMENT / PROMOTION_DURATION ) AS LEASE_FEE, DOWN_PAYMENT LEASE_AMOUNT, DOWN_PAYMENT TOTAL_AMOUNT, DECODE(SERVICE_TYPE, 2, 'LEASE') AS SALE_TYPE, IS_COMPLETE  FROM (
SELECT CARD_NO, STB_NO, BUNDLE_ID, BUNDLE_NAME, PRICE BASIC_AMOUNT, 0 DISCOUNT, ( DEPOSIT_PERCENT / 100 * PRICE ) DOWN_PAYMENT, SERVICE_TYPE, IS_COMPLETE FROM (
SELECT CARD_NO, STB_NO, BUNDLE_ID, BUNDLE_NAME, PRICE, DEPOSIT_PERCENT, DEPOSIT_PRICE, SERVICE_TYPE, IS_COMPLETE FROM T_DISH_CUSTOM_BRIEF A LEFT JOIN W_BUNDLE B ON A.BUNDLE_ID = B.ID WHERE A.IS_PREPAID = 2 --AND CARD_NO NOT LIKE '100%'
) WHERE SERVICE_TYPE = 2 ) A LEFT JOIN W_BUNDLE_PROMOTION B ON A.BUNDLE_ID = B.BUNDLE_ID
) UNION ALL (
SELECT CARD_NO, STB_NO, BUNDLE_ID, BUNDLE_NAME, BASIC_AMOUNT, DISCOUNT, DOWN_PAYMENT SALE_AMOUNT, DOWN_PAYMENT, 0 LEASE_PERIOD, 0 LEASE_FEE, 0 LEASE_AMOUNT, DOWN_PAYMENT TOTAL_AMOUNT, DECODE(SERVICE_TYPE, 4, 'CONTRACT') AS SALE_TYPE, IS_COMPLETE FROM (
SELECT CARD_NO, STB_NO, BUNDLE_ID, BUNDLE_NAME, PRICE AS BASIC_AMOUNT, 0 DISCOUNT, ( PRICE - DEPOSIT_PRICE ) DOWN_PAYMENT, SERVICE_TYPE, IS_COMPLETE FROM T_DISH_CUSTOM_BRIEF A LEFT JOIN W_BUNDLE B ON A.BUNDLE_ID = B.ID WHERE A.IS_PREPAID = 2 AND CARD_NO NOT LIKE '100%'
) WHERE SERVICE_TYPE = 4
) ) A LEFT JOIN POSTPAID_SUBSCRIBER B ON A.CARD_NO = B.CARD_NO WHERE GER_NUMBER IS NOT NULL
) UNION ALL (
--DEVICE_NOT_REQUIRED
SELECT CARD_NO CARD_NUMBER, PRODUCT_ID, POLICY_ID, POLICY_NAME, GER_NUMBER, CONTRACT_ID, CONNECT_TIME, BASIC_AMOUNT, DISCOUNT, SALE_AMOUNT, DOWN_PAYMENT, LEASE_PERIOD, LEASE_FEE, LEASE_AMOUNT, TOTAL_AMOUNT, SALE_TYPE, IS_COMPLETE FROM (
SELECT CARD_NO, PRODUCT_ID, POLICY_ID, POLICY_NAME, GER_NUMBER, CONTRACT_ID, CONNECTED_DATE AS CONNECT_TIME, 0 BASIC_AMOUNT, 0 DISCOUNT, 0 SALE_AMOUNT, 0 DOWN_PAYMENT, 0 LEASE_PERIOD, 0 LEASE_FEE, 0 LEASE_AMOUNT, 0 TOTAL_AMOUNT, '0' SALE_TYPE, 0 IS_COMPLETE
FROM POSTPAID_SUBSCRIBER WHERE POLICY_ID = 1 
) UNION ALL (
SELECT CARD_NO, PRODUCT_ID, POLICY_ID, POLICY_NAME, GER_NUMBER, CONTRACT_ID, CONNECTED_DATE AS CONNECT_TIME, PRICE BASIC_AMOUNT, 0 DISCOUNT, PRICE SALE_AMOUNT, 0 DOWN_PAYMENT, 0 LEASE_PERIOD, 0 LEASE_FEE, 0 LEASE_AMOUNT, PRICE TOTAL_AMOUNT, DECODE(SERVICE_TYPE, 1, 'CASH') AS SALE_TYPE, 0 IS_COMPLETE
FROM POSTPAID_SUBSCRIBER A LEFT JOIN W_BUNDLE B ON A.POLICY_ID = B.ID WHERE POLICY_ID != 1 AND CAT3 = 1 AND SERVICE_TYPE = 1 
) UNION ALL (
SELECT CARD_NO, PRODUCT_ID, POLICY_ID, POLICY_NAME, GER_NUMBER, CONTRACT_ID, CONNECT_TIME, BASIC_AMOUNT, DISCOUNT, DOWN_PAYMENT SALE_AMOUNT, DOWN_PAYMENT, PROMOTION_DURATION AS LEASE_PERIOD, ( DOWN_PAYMENT / PROMOTION_DURATION ) LEASE_FEE, DOWN_PAYMENT LEASE_AMOUNT, DOWN_PAYMENT TOTAL_AMOUNT, DECODE(SERVICE_TYPE, 2, 'LEASE') AS SALE_TYPE, IS_COMPLETE FROM (
SELECT CARD_NO, PRODUCT_ID, POLICY_ID, POLICY_NAME, GER_NUMBER, CONTRACT_ID, CONNECTED_DATE AS CONNECT_TIME, PRICE BASIC_AMOUNT, 0 DISCOUNT, ( DEPOSIT_PERCENT / 100 * PRICE ) DOWN_PAYMENT, SERVICE_TYPE, IS_COMPLETE
FROM POSTPAID_SUBSCRIBER A LEFT JOIN W_BUNDLE B ON A.POLICY_ID = B.ID WHERE POLICY_ID != 1 AND CAT3 = 1 AND SERVICE_TYPE = 2
) A LEFT JOIN W_BUNDLE_PROMOTION B ON A.POLICY_ID = B.BUNDLE_ID 
) UNION ALL (
SELECT CARD_NO, PRODUCT_ID, POLICY_ID, POLICY_NAME, GER_NUMBER, CONTRACT_ID, CONNECT_TIME, BASIC_AMOUNT, DISCOUNT, DOWN_PAYMENT SALE_AMOUNT, DOWN_PAYMENT, 0 LEASE_PERIOD, 0 LEASE_FEE, DOWN_PAYMENT LEASE_AMOUNT, DOWN_PAYMENT TOTAL_AMOUNT, DECODE(SERVICE_TYPE, 4, 'CONTRACT') AS SALE_TYPE, IS_COMPLETE FROM (
SELECT CARD_NO, PRODUCT_ID, POLICY_ID, POLICY_NAME, GER_NUMBER, CONTRACT_ID, CONNECTED_DATE CONNECT_TIME, PRICE AS BASIC_AMOUNT, 0 DISCOUNT, ( PRICE - DEPOSIT_PRICE ) DOWN_PAYMENT, SERVICE_TYPE, IS_COMPLETE
FROM POSTPAID_SUBSCRIBER A LEFT JOIN W_BUNDLE B ON A.POLICY_ID = B.ID WHERE POLICY_ID != 1 AND CAT3 = 1 AND SERVICE_TYPE = 4 ) )
)
) A 
LEFT JOIN T_DISH_CUSTOM B ON A.CARD_NUMBER = B.CARD_NO
LEFT JOIN ADMIN_NUMBER C ON A.CARD_NUMBER = C.CARD_NO
LEFT JOIN PRODUCT_CATALOG D ON A.PRODUCT_ID = D.PRODUCT_ID
LEFT JOIN SYSTEM_YES_USER_TBL E ON B.OPERATION_ID = E.USER_NAME
LEFT JOIN SYSTEM_BRANCH_LOCATION F ON E.BRANCH_ID = F.BRANCH_ID WHERE CONTRACT_ID IS NOT NULL AND CARD_NUMBER NOT LIKE '100%'", begin, end);
            return qry;
        }

        public static string login(string username)
        {
            string qry = string.Format(@"select USER_FIRST_NAME, USER_PASSWORD, USER_EMAIL from DREPORT_LOGIN where USER_PHONE='{0}'", username);
            return qry;
        }
    }
}
